import { CheckInHabit, CheckInLog, Collection, MediaItem, TagDefinition } from '../types';
import { generateSvgCover } from './helpers';

export const DEFAULT_TAG_DEFINITIONS: TagDefinition[] = [
  { id: 'tag-test-global', name: '解析测试', mediaType: 'global' },
  { id: 'tag-test-cover-ok', name: '封面正常', mediaType: 'global' },
  { id: 'tag-test-cover-missing', name: '封面待修复', mediaType: 'global' },
  { id: 'tag-test-creator-ok', name: '主创正常', mediaType: 'global' },
  { id: 'tag-test-description-ok', name: '描述正常', mediaType: 'global' },
  { id: 'tag-test-cn', name: '中文转码验证', mediaType: 'global' },
  { id: 'tag-source-douban', name: '豆瓣', mediaType: 'global' },
  { id: 'tag-source-imdb', name: 'IMDb', mediaType: 'global' },
  { id: 'tag-source-steam', name: 'Steam', mediaType: 'global' },
  { id: 'tag-source-apple', name: 'Apple Music', mediaType: 'global' },
  { id: 'tag-source-netease', name: '网易云音乐', mediaType: 'global' },
  { id: 'tag-source-wiki', name: '维基百科', mediaType: 'global' },
  { id: 'tag-book-parse', name: '图书解析', mediaType: 'book' },
  { id: 'tag-movie-parse', name: '电影解析', mediaType: 'movie' },
  { id: 'tag-music-parse', name: '音乐解析', mediaType: 'music' },
  { id: 'tag-game-parse', name: '游戏解析', mediaType: 'game' },
];

export const DEFAULT_COLLECTIONS: Collection[] = [
  {
    id: 'col-parse-all',
    name: '链接解析验证',
    description: '管理员用于检查名称、主创、描述、评分、封面和来源链接的测试合集。',
    createdAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'col-parse-douban',
    name: '豆瓣解析样本',
    description: '豆瓣电影、图书、音乐、游戏链接解析结果。',
    createdAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'col-parse-music-game',
    name: '音乐与游戏样本',
    description: 'Apple Music、网易云音乐和 Steam 的解析结果。',
    createdAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'col-parse-international',
    name: '国际站点样本',
    description: 'IMDb、Steam、Apple Music、维基百科等非豆瓣来源。',
    createdAt: '2026-07-24T00:00:00.000Z',
  },
];

export const DEFAULT_MEDIA_ITEMS: MediaItem[] = [
  {
    id: 'test-douban-movie-shawshank',
    title: '肖申克的救赎',
    originalTitle: 'The Shawshank Redemption',
    type: 'movie',
    creator: '弗兰克·德拉邦特',
    coverUrl: 'https://img9.doubanio.com/view/photo/l_ratio_poster/public/p480747492.webp',
    description: '恐惧让你沦为囚犯，希望让你重获自由。用于验证豆瓣电影的标题、导演、评分和封面。',
    sourceUrl: 'https://movie.douban.com/subject/1292052/',
    status: 'completed',
    completedDate: '2026-07-24',
    reReadCount: 0,
    reReadLogs: [],
    personalRating: 9.7,
    personalNote: '管理员解析测试样本。',
    noteImages: [],
    tags: ['解析测试', '豆瓣', '电影解析', '主创正常', '描述正常', '中文转码验证'],
    collections: ['col-parse-all', 'col-parse-douban'],
    createdAt: '2026-07-24T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'test-douban-book-prince',
    title: '小王子',
    originalTitle: 'Le Petit Prince',
    type: 'book',
    creator: '[法国] 安东尼·德·圣-埃克苏佩里',
    coverUrl: 'https://img1.doubanio.com/view/subject/l/public/s1237549.jpg',
    description: '小王子告别自己的星球，开始遨游太空的旅行。用于验证豆瓣图书的作者、简介和封面。',
    sourceUrl: 'https://book.douban.com/subject/1084336/',
    status: 'completed',
    completedDate: '2026-07-24',
    reReadCount: 0,
    reReadLogs: [],
    personalRating: 9.1,
    personalNote: '管理员解析测试样本。',
    noteImages: [],
    tags: ['解析测试', '豆瓣', '图书解析', '封面正常', '主创正常', '描述正常', '中文转码验证'],
    collections: ['col-parse-all', 'col-parse-douban'],
    createdAt: '2026-07-24T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'test-douban-music-fantasy',
    title: '范特西',
    type: 'music',
    creator: '周杰伦',
    coverUrl: 'https://img1.doubanio.com/view/subject/m/public/s35019288.jpg',
    description: '周杰伦第二张录音室专辑。用于验证豆瓣音乐的歌手、发行信息、评分和封面。',
    sourceUrl: 'https://music.douban.com/subject/1403307/',
    status: 'completed',
    completedDate: '2026-07-24',
    reReadCount: 0,
    reReadLogs: [],
    personalRating: 9.5,
    personalNote: '管理员解析测试样本。',
    noteImages: [],
    tags: ['解析测试', '豆瓣', '音乐解析', '封面正常', '主创正常', '描述正常', '中文转码验证'],
    collections: ['col-parse-all', 'col-parse-douban', 'col-parse-music-game'],
    createdAt: '2026-07-24T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'test-douban-game-zelda',
    title: '塞尔达传说 旷野之息',
    originalTitle: 'ゼルダの伝説 ブレス オブ ザ ワイルド',
    type: 'game',
    creator: '',
    coverUrl: generateSvgCover('塞尔达传说 旷野之息', 'Nintendo', 'game'),
    description: '用于验证豆瓣游戏链接。当前豆瓣游戏页面经常缺少制作方和封面，需要继续修复。',
    sourceUrl: 'https://m.douban.com/game/subject/26817171/',
    status: 'completed',
    completedDate: '2026-07-24',
    reReadCount: 0,
    reReadLogs: [],
    personalRating: 9.8,
    personalNote: '管理员解析测试样本：豆瓣游戏制作方和封面仍需继续修复。',
    noteImages: [],
    tags: ['解析测试', '豆瓣', '游戏解析', '封面待修复', '描述正常', '中文转码验证'],
    collections: ['col-parse-all', 'col-parse-douban', 'col-parse-music-game'],
    createdAt: '2026-07-24T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'test-steam-elden-ring',
    title: '艾尔登法环',
    originalTitle: 'ELDEN RING',
    type: 'game',
    creator: 'FromSoftware, Inc.',
    coverUrl: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg',
    description: '以辽阔场景与地下迷宫探索未知、挑战强敌的动作角色扮演游戏。用于验证 Steam 游戏解析。',
    sourceUrl: 'https://store.steampowered.com/app/1245620/ELDEN_RING/',
    status: 'completed',
    completedDate: '2026-07-24',
    reReadCount: 0,
    reReadLogs: [],
    personalRating: 9,
    personalNote: '管理员解析测试样本。',
    noteImages: [],
    tags: ['解析测试', 'Steam', '游戏解析', '封面正常', '主创正常', '描述正常'],
    collections: ['col-parse-all', 'col-parse-music-game', 'col-parse-international'],
    createdAt: '2026-07-24T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'test-apple-random-access',
    title: 'Random Access Memories',
    type: 'music',
    creator: 'Daft Punk',
    coverUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/e8/43/5f/e8435ffa-b6b9-b171-40ab-4ff3959ab661/886443919266.jpg/600x600bb.jpg',
    description: 'Pop / 发行时间：2013-05-17。用于验证 Apple Music 专辑解析。',
    sourceUrl: 'https://music.apple.com/us/album/random-access-memories/617154241',
    status: 'completed',
    completedDate: '2026-07-24',
    reReadCount: 0,
    reReadLogs: [],
    personalRating: 8.8,
    personalNote: '管理员解析测试样本。',
    noteImages: [],
    tags: ['解析测试', 'Apple Music', '音乐解析', '封面正常', '主创正常', '描述正常'],
    collections: ['col-parse-all', 'col-parse-music-game', 'col-parse-international'],
    createdAt: '2026-07-24T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'test-netease-qingtian',
    title: '晴天',
    type: 'music',
    creator: '周杰伦',
    coverUrl: 'http://p2.music.126.net/ZGffiDQZrGj5s_hnR1CNbg==/109951165566379710.jpg',
    description: '歌曲名《晴天》，由周杰伦演唱，收录于《叶惠美》专辑中。用于验证网易云音乐歌曲解析。',
    sourceUrl: 'https://music.163.com/#/song?id=186016',
    status: 'completed',
    completedDate: '2026-07-24',
    reReadCount: 0,
    reReadLogs: [],
    personalRating: 8.5,
    personalNote: '管理员解析测试样本。',
    noteImages: [],
    tags: ['解析测试', '网易云音乐', '音乐解析', '封面正常', '主创正常', '描述正常', '中文转码验证'],
    collections: ['col-parse-all', 'col-parse-music-game'],
    createdAt: '2026-07-24T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
  {
    id: 'test-wikipedia-three-body',
    title: '三体',
    originalTitle: '三体 (小说)',
    type: 'book',
    creator: '刘慈欣',
    coverUrl: generateSvgCover('三体', '刘慈欣', 'book'),
    description: '维基百科中文条目用于验证中文 URL 转码和百科类页面解析。当前服务器侧访问维基百科可能超时，保留为待继续验证样本。',
    sourceUrl: 'https://zh.wikipedia.org/wiki/%E4%B8%89%E4%BD%93_(%E5%B0%8F%E8%AF%B4)',
    status: 'completed',
    completedDate: '2026-07-24',
    reReadCount: 0,
    reReadLogs: [],
    personalRating: 9,
    personalNote: '管理员解析测试样本：维基百科连通性需要在线环境继续验证。',
    noteImages: [],
    tags: ['解析测试', '维基百科', '图书解析', '封面待修复', '主创正常', '描述正常', '中文转码验证'],
    collections: ['col-parse-all', 'col-parse-international'],
    createdAt: '2026-07-24T00:00:00.000Z',
    updatedAt: '2026-07-24T00:00:00.000Z',
  },
];

export const DEFAULT_HABITS: CheckInHabit[] = [
  { id: 'habit-book', name: '图书', color: 'emerald', mediaType: 'book' },
  { id: 'habit-movie', name: '电影', color: 'blue', mediaType: 'movie' },
  { id: 'habit-music', name: '音乐', color: 'pink', mediaType: 'music' },
  { id: 'habit-game', name: '游戏', color: 'amber', mediaType: 'game' },
];

export const DEFAULT_CHECK_IN_LOGS: CheckInLog[] = [];
